### ISSUE TITLE
More about last request

### ISSUE THREAD

**Issue by yhstsy** [bnojavan/EmoReact#2]
I have already filled out the form for applying for the dataset, but I don't know when I will be able to pass the processing results of the form. Our project will be completed in one month. Please lend us a helping hand... @bnojavan

**Comment by bnojavan** [comment]
What email address have you used for filling the form? If it is not university domain email, the data cannot be released. If you have filled the form a while back and have not received the data, you probably have used a personal email. Please refill the form considering the given instruction and your university domain email and get access to data.
